spring:
  application:
    name: Manager Products
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PWD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway: #flyway automatically uses the datasource from the application to connect to the DB
    enabled: true # enables flyway database migration
    locations: classpath:db/migration/structure, classpath:db/migration/data # the location where flyway should look for migration scripts
    validate-on-migrate: true
    default-schema: manager
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

server:
  port: ${PORT}

springdoc:
  api-docs:
    path: /api/documentation
  swagger-ui:
    path: /swagger-ui.html
    enable: true
  show-actuator: true
  packages-to-scan: com.vsouza.managerproducts.controllers


rabbit-queues:
  message-queue: ${RABBITMQ_QUEUE_NAME}
  exchange-message: ${RABBITMQ_EXCHANGE}
  exchange-route-key: ${RABBITMQ_ROUTING_KEY}

